"""
Texts to be displayed

"""

import emoji

texts_raw = {

"WELCOME": "Hola, soy tu avisador personal de billetes de Renfe.",
"NOT_AUTH_REPLY": "Hola, {username}, por ahora no estás autorizado a usar este servicio. "
                    "Solicitando acceso a admin. Por favor, intentalo dentro de unos minutos.",
"ADMIN_USER_REQ_ACCESS": "Usuario {username} solicita acceso",
"END_MESSAGE": "Gracias por usar Train Notifier Bot, escribe /start para empezar de nuevo",
"OPTION_SELECTION": "Hola, ¿qué quieres hacer?",
"MAIN_OP_SEARCH" : "Realizar búsqueda",
"MAIN_OP_VIEW_FOLLOWUPS":"Ver seguimientos activos",
"MAIN_OP_UNKNOWN": "Lo siento, no te he entendido. ",
"DO_ONETIME_QUERY": "Perfecto, vamos a buscar un tren.",
"FOLLOWUPS_EMPTY": "No tienes seguimientos activos.",
"FOLLOWUPS_LIST": "Tus seguimientos activos son:\n{items}",
"FOLLOWUPS_DELETE_ASK": "¿Quieres eliminar algún seguimiento? (SI/NO)",
"FOLLOWUPS_DELETE_PROMPT": "Indica el número del seguimiento que quieres eliminar.",
"FOLLOWUPS_DELETED": "Seguimiento eliminado.",
"FOLLOWUPS_DELETE_INVALID": "Número inválido. Escribe un número de la lista.",
"SELECT_ORIGIN_STATION": "Escribe la estación de origen :station:.",
"SELECT_DESTINATION_STATION": "Escribe la estación de destino :station:.",
"STATION_TARGET_ORIGIN": "origen",
"STATION_TARGET_DESTINATION": "destino",
"STATION_PICKER_HELP": "Busca estación de {target}. Escribe parte del nombre y selecciona en la lista.",
"STATION_PICKER_PROMPT": "Selecciona estación de {target} (o escribe para filtrar).",
"STATION_PICKER_RESULTS": "Selecciona estación de {target}. Filtro: '{query}' ({count} resultados).",
"STATION_PICKER_EMPTY": "No hay coincidencias para '{query}' en {target}. Escribe otro texto para filtrar.",
"STATION_PICKER_CANCEL": "Cancelar búsqueda",
"STATION_SELECTED": "Estación de {target} seleccionada: {station}.",
"INVALID_STATION": "No reconozco la estación '{station}'. Revisa el nombre e inténtalo otra vez. Puedes usar alguna de estas estaciones: {suggestions}.",
"GROUP_STATION_OPTIONS": "Has seleccionado '{station_group}'. En {city} hay {count} estaciones concretas:\n{options}\n{all_option_number}. Buscar por todas ({station_group})\nResponde con el número de opción.",
"GROUP_STATION_NO_CONCRETE": "(No se han encontrado estaciones concretas para esta ciudad en el catálogo)",
"GROUP_STATION_INVALID_OPTION": "Opción inválida. Escribe un número válido de la lista.",
"GROUP_STATION_ALL_WARNING": "Se buscará usando '{station_group}'. Puede haber errores al filtrar por varias estaciones a la vez; se recomienda seleccionar una estación concreta.",
"SELECT_TRIP_DATE": "Elige ahora la fecha del viaje :date:.",
"INVALID_DATE_RANGE": "La fecha seleccionada no es válida. Solo puedes elegir desde hoy hasta dentro de 2 meses.",
"SELECTED_TRIP": "Has seleccionado el trayecto {origin} -> {destination}.",
"SELECTED_DATA": "Perfecto, has seleccionado el trayecto {origin} -> {destination}"
                    " para el día {date}.",
"WAIT_FOR_TRAINS": "Espera mientras busco trenes :train:. (Puede tardar un poco...).",
"NO_TRAINS_FOUND": "No hay trenes para el trayecto {origin} -> {destination} para el día {date}.",
"NO_TRAINS_FOUND_PLAZA_H": "No hay trenes con Plaza H disponible para el trayecto {origin} -> {destination} para el día {date}.",
"TRAIN_INFO": "De {t_departure} a {t_arrival}, {cost}€, T: {ticket_type}",
"QUERY_IN_DB": "{date}: {origin} -> {destination}",
"ASK_PLAZA_H": "¿Quieres buscar con Plaza H disponible?",
"MAIN_OP_PLAZA_H_YES": "Sí, Plaza H disponible",
"MAIN_OP_PLAZA_H_NO": "No, plazas estándar",
"ASK_SEARCH_MODE": "¿Qué quieres consultar?",
"MAIN_OP_MODE_SPECIFIC": "Hora concreta",
"MAIN_OP_MODE_FIRST": "Primer tren disponible",
"MAIN_OP_MODE_LAST": "Último tren disponible",
"MAIN_OP_MODE_ALL": "Todas las opciones",
"TRAIN_SELECT_PROMPT": "Selecciona una opción:\n{options}",
"TRAIN_SELECT_ALL_OPTION": "Todos los trenes",
"TRAIN_SELECT_INVALID": "Opción inválida. Escribe un número válido.",
"TRAIN_PICKER_HELP": "Selecciona un tren (4 por página).",
"TRAIN_PICKER_PROMPT": "Trenes {start}-{end} de {total}",
"TRAIN_PICKER_USE_BUTTONS": "Por favor, usa los botones del menú anterior para seleccionar.",
"ASK_ADDITIONAL_SAME_STATIONS": "¿Deseas usar las mismas estaciones de origen y destino? (SI/NO)",
"ASK_ADDITIONAL_SAME_DATE": "¿Deseas usar la misma fecha? (SI/NO)",
"TRAIN_AVAILABLE_MSG": "Felicidades! El tren del día {date} {origin} ({dep_time}) - {destination}({arr_time}) tiene plazas disponibles.",
"TRAIN_NOT_AVAILABLE_MSG": "Lo lamentamos, El tren del día {date} {origin} ({dep_time}) - {destination}({arr_time}) NO tiene plazas disponibles. ¿Quieres hacer un seguimiento? (SI/NO)",
"TRAIN_NOT_AVAILABLE_ALL_MSG": "Lo lamentamos, Ningún tren del día {date} {origin} - {destination} tiene plazas disponibles. ¿Quieres hacer un seguimiento? (SI/NO)",
"FOLLOWUP_CREATED_MSG": "De acuerdo, se hará seguimiento al tren del día {date} {origin} ({dep_time}) - {destination}({arr_time}). Se te avisará tan pronto como haya plazas disponibles.",
"FOLLOWUP_CREATED_ALL_MSG": "De acuerdo, se hará seguimiento a todos los trenes del día {date} {origin} - {destination}. Se te avisará tan pronto como haya plazas disponibles.",
"FOLLOWUP_AVAILABLE_MSG": "Felicidades! El tren con seguimiento {date} {origin} ({dep_time}) - {destination}({arr_time}) tiene plazas disponibles.",
"FOLLOWUP_AVAILABLE_ALL_MSG": "Felicidades! El seguimiento de {date} {origin} - {destination} ha encontrado trenes con plazas disponibles.",
"FOLLOWUP_EXPIRED_MONTH_MSG": "El seguimiento {date} {origin} ({dep_time}) - {destination}({arr_time}) ha alcanzado 1 mes. ¿Quieres prolongarlo? (SI/NO)",
"FOLLOWUP_EXTEND_PROMPT": "El seguimiento {date} {origin} ({dep_time}) - {destination}({arr_time}) está pendiente de ampliación. ¿Quieres prolongarlo 1 mes? (SI/NO)",
"FOLLOWUP_EXTENDED_MSG": "Seguimiento prolongado.",
"FOLLOWUP_NOT_EXTENDED_MSG": "Seguimiento finalizado sin ampliación.",
"FOLLOWUP_EXPIRED_DEPARTURE_MSG": "Se ha borrado el seguimiento {date} {origin} ({dep_time}) - {destination}({arr_time}) porque el tren ya ha efectuado su salida en origen.",
"FOLLOWUP_NO_PENDING": "No tienes ninguna ampliación pendiente.",
"ASK_FOLLOWUP_CONFIRM": "¿Quieres hacer seguimiento? (SI/NO)",
"ASK_ADDITIONAL_QUERY": "¿Quieres hacer alguna consulta adicional? (SI/NO)",
"RECOVERY_OPTIONS_PROMPT": "No se ha encontrado disponibilidad para la opción actual. ¿Qué quieres hacer?",
"RECOVERY_OP_RETRY_MODE": "Volver a opciones de búsqueda",
"RECOVERY_OP_CHANGE_DATE": "Cambiar fecha",
"RECOVERY_OP_MAIN_MENU": "Volver al menú principal",
"RECOVERY_INVALID_OPTION": "Opción no válida. Elige una de las opciones mostradas.",
"MAIN_OP_YES": "SI",
"MAIN_OP_NO": "NO",
"NO_AVAILABLE_TRIPS_LIST": "ninguno",
"CANCEL" : "Cancelar",
"FOLLOWUP_NOTIFYING_AVAILABLE_MSG": "Felicidades: Tu tren \"{origin} - {destination} ({date} {dep_time})\" ya tiene plazas disponibles. En caso de querer detener el seguimiento y el envio del mensaje, escriba /stop",
"STATS_TITLE": "📊 Total de consultas realizadas hasta el momento:",
"DAILY_STATS_TITLE": "📊 Resumen diario de consultas (00:00):",
"STATS_ITEM": "{index}. {origin} - {destination} ({date} {dep_time}): {daily} consultas ({total} consultas en total)",
"STATS_EMPTY": "No tienes seguimientos activos en este momento.",
"STOP_SUCCESS": "🛑 Se ha detenido el seguimiento y el envío de avisos para:\n{items}",
"STOP_EMPTY": "No tienes ningún seguimiento activo con avisos de plazas disponibles pendientes de detener con /stop."
}

texts = {}
for t in texts_raw:
    texts[t] = emoji.emojize(texts_raw[t], language="alias")

keyboards = {
"MAIN_OPTIONS": [[texts["MAIN_OP_SEARCH"]],
                [texts["MAIN_OP_VIEW_FOLLOWUPS"]]
                ]
,
"PLAZA_H_OPTIONS": [[texts["MAIN_OP_PLAZA_H_YES"]],
                    [texts["MAIN_OP_PLAZA_H_NO"]]],
"SEARCH_MODE_OPTIONS": [[texts["MAIN_OP_MODE_SPECIFIC"]],
                        [texts["MAIN_OP_MODE_FIRST"]],
                        [texts["MAIN_OP_MODE_LAST"]],
                        [texts["MAIN_OP_MODE_ALL"]]],
"RECOVERY_OPTIONS": [[texts["RECOVERY_OP_RETRY_MODE"]],
                    [texts["RECOVERY_OP_CHANGE_DATE"]],
                    [texts["RECOVERY_OP_MAIN_MENU"]]],
"YES_NO_OPTIONS": [[texts["MAIN_OP_YES"]],
                   [texts["MAIN_OP_NO"]]]
}
